server:
  port: 8081
spring:
  application:
    name: demo-java
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1.0
logging:
  level:
    root: INFO
    org:
      springframework.web: DEBUG
debug: true
