server:
  port: 8070
spring:
  application:
    name: shop-sidecar
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true
sidecar:
  port: 3000                                      # Node.js微服务的端口
  health-uri: http://localhost:3000/health.json   # Node.js微服务的健康检查URL